# Generated by Django 5.2 on 2026-09-04 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('patient', 'New Patient'), ('appointment', 'New Appointment'), ('payment', 'Payment Received'), ('completed', 'Appointment Completed')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['-created_at'],
            },
        ),
    ]
